---
title: "Tesla Back On Track: In-depth analytics to uncover potential markets and raise market share"
to:
  - name: Mark Kyle Castro
    role: "Chief Marketing/Sales Officer"
    company: Tesla
authors:
  - name: Ben Hsiao (5133) 
    role: "Student"
    email: jh5133@columbia.edu 
    affiliations:
      - name: Columbia University
  - name: Agustina Kohen (5501)
    role: "Student"
    email: ak5501@columbia.edu
    affiliations:
      - name: Columbia University
date: 12/3/2025
date-format: long
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
  html:
    toc: true
    number-sections: true
    code-fold: show
    code-tools: true
    code-link: true
    theme:
      light: flatly
      dark: darkly
    embed-resources: true
execute:
  eval: true
  warning: false
  message: false
  error: false
  echo: true
---

# Preliminary setup {-}

Load libraries to access functions we'll use in this analysis.


```{r}
library(tidyverse) # the usual

```

# Introduction

Road transportation is a major contributor to urban air pollution, and recent data indicate that cars and vans account for 48% of global transportation CO₂ emissions—the largest share among all transportation modes [5]. As Tesla works to accelerate the transition to sustainable energy, this challenge also highlights a strategic opportunity: **many of the most polluted U.S. regions continue to have low EV adoption and limited charging access, restricting both environmental gains and market growth.**

To fully understand the strategic potential of this analysis, it is important to consider current EV adoption trends and the specific information gaps that constrain Tesla’s ability to seize these opportunities. Tesla has proven to be an innovative and leading organization in the transportation sector. Tesla's brand is viewed as both luxurious and sustainable, appealing to a diverse range of customers. However, as the end of the year approaches, the EV market share in the United States had decreased to 7.4% by Q2 2025, indicating a year-over-year decline. Tesla’s market share in the EV market increased to 46%, but sales continue to decline by 10% annually [4]. The growth of sustainability-conscious consumers should lead to a boost in the EV market. 

## The approach

Tesla currently lacks a data-driven approach that compares the US counties with high air pollution and low EV adoption. To address this gap, let us delve into a data analysis that combines EPA Air Quality System (AQS) data, Department of Energy EV registration data, and charging infrastructure records, thereby providing a holistic understanding of how EV adoption relates to air-quality improvements and validating these patterns across regions. The resulting insights will guide Supercharger placement, targeted marketing, and public-sector partnerships—helping Tesla prioritize high-impact, underserved markets while advancing measurable progress toward its sustainability mission.

## Understanding the data

For the purpose of this analysis, we will primarily work with three datasets. One is the EPA’s Air Quality System (AQS), which includes PM2.5, NO₂, and daily AQI readings. The next one is EV-registration data from the Department of Energy. The last one is public EV charging station data, also from the Department of Energy. Our first step is to clean all datasets, match the time periods, and align them using the same geographic identifiers so that the regions correspond correctly. 

Next, we will examine **three key questions:** 
- Which states represent the highest-opportunity markets for Tesla? (given their high pollution and low EV adoption)
- From the high-opportunity markets, which have low access to EV charging stations?
- How can changing the station infrastructure affect pollution and Tesla's revenue?


# Which states represent the highest-opportunity markets for Tesla because of their pollution rates?


# Is it accessible for people to obtain an EV, and should we target the construction of charging stations as a solution to this problem? 


# If we target those markets, what would be the estimated pollution reduction/The estimated revenue increase


# Final Thoughts

# References cited {-}

[1] Electric vehicle registrations and consumption. Electric Vehicle Registrations and Consumption | Bureau of Transportation Statistics. (n.d.). https://www.bts.gov/browse-statistical-products-and-data/state-transportation-statistics/electric-vehicle-registrations 
[2] Environmental Protection Agency. (n.d.-a). Air Quality - Cities and Counties. EPA. https://www.epa.gov/air-trends/air-quality-cities-and-counties 
[3] Environmental Protection Agency. (n.d.-b). AirData website. EPA. https://aqs.epa.gov/aqsweb/documents/data_api.html 
[4] Fischer, J. (2025, November 26). Electric vehicle sales and market share (US - Q3 2025 updates). CarEdge. https://caredge.com/guides/electric-vehicle-market-share-and-sales#Q3_2025_EV_Sales_Totals_In_Progres 
[5] Fleck, A., & Richter, F. (2023, September 22). Infographic: Cars cause biggest share of Transportation co₂ emissions. Statista Daily Data. https://www.statista.com/chart/30890/estimated-share-of-co2-emissions-in-the-transportation-sector/ 
[6] Maps and data - electric vehicle registrations by State. Alternative Fuels Data Center: Maps and Data - Electric Vehicle Registrations by State. (n.d.). https://afdc.energy.gov/data/10962




# Submission --- reproducibility {-}


